services:
  frontend:
    build:
      context: ./src/client
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./src/client:/app
      - /app/node_modules

  backend:
    build:
      context: ./src/server
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./src/server:/app
      - /app/node_modules

networks:
  default:
    driver: bridge
