version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://api.yourdomain.com

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

networks:
  default:
    driver: bridge
